# Generated by Django 4.1.7 on 2023-03-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espn_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='NbaPlayer',
        ),
        migrations.CreateModel(
            name='NbaTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='espn_app.nbaplayer')),
            ],
        ),
    ]
