# Generated by Django 4.1.7 on 2023-03-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espn_app', '0002_rename_player_nbaplayer_nbateam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='members',
        ),
        migrations.DeleteModel(
            name='NbaPlayer',
        ),
        migrations.DeleteModel(
            name='NbaTeam',
        ),
    ]
