# Generated by Django 4.1.7 on 2023-03-07 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espn_app', '0003_remove_nbateam_members_delete_nbaplayer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=18)),
                ('full_name', models.CharField(max_length=24)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=3)),
                ('nickname', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=13)),
                ('state', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=22)),
                ('year_founded', models.IntegerField()),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='espn_app.players')),
                ('season_id', models.CharField(max_length=7)),
                ('player_age', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('games_started', models.IntegerField()),
                ('minutes_played', models.IntegerField()),
                ('field_goals_made', models.IntegerField()),
                ('field_goals_attempted', models.IntegerField()),
                ('field_goal_percentage', models.DecimalField(decimal_places=3, max_digits=4)),
                ('three_pointers_made', models.IntegerField()),
                ('three_pointers_attempted', models.IntegerField()),
                ('three_pointer_percentage', models.DecimalField(decimal_places=3, max_digits=4)),
                ('free_throws_made', models.IntegerField()),
                ('free_throws_attempted', models.IntegerField()),
                ('free_throw_percentage', models.DecimalField(decimal_places=3, max_digits=4)),
                ('offensive_rebounds', models.IntegerField()),
                ('defensive_rebounds', models.IntegerField()),
                ('rebounds', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('personal_fouls', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'player_season_stats',
                'managed': False,
            },
        ),
    ]
