# Generated by Django 4.1.7 on 2023-03-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espn_app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=18)),
                ('full_name', models.CharField(max_length=24)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=3)),
                ('nickname', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=13)),
                ('state', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=22)),
                ('year_founded', models.IntegerField()),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
